# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
nix = { version = "0.30.1", features = ["fs", "socket"] }